---
- name: remove httpd
  hosts: all
  become: true
  tasks:
  - name: stop service
    service: 
      name: httpd
      state: stopped
      enabled: no
  - name: remove httpd
    yum:
      name: httpd
      state: absent
